# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: configuration@1
  inputs:
    connection: 'LT_NEW'
    isTunnelActivate: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      pip install robotframework
      pip install robotframework-pabot
      pip install robotframework-appiumlibrary
      cd app/test
      robot Appium_android.robot

